### ISSUE TITLE
Analysis of MazF data

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/JACUSA2#28]
Please take a look at /prj/JACUSA2_TestField/Chuang_He_m6A/workflow_mouse/JACUSA2

I have computed call2_RNA_MazF_noDedup_RC15_rtarrest_plain_result.out
by

## JACUSA2 Version: 2.0.0-RC15 rt-arrest -F 1024 -c 4 -p 10 -P1 FR-SECONDSTRAND -P2 FR-SECONDSTRAND -r call2_RNA_MazF_noDedup_RC15_rtarrest_plain_result.out SRR8450822_STARmapping_uniq.bam SRR8450821_STARmapping_uniq.bam

I am a bit puzzled by some results like:
MT    11420 11421
 rt-arrest 0.0 - 0,0,17,0 0,0,6997,0   *       0,0,6,0 arrest_score=105.80704611567853 * G

![MT_igv_snapshot](https://user-images.githubusercontent.com/7941393/78025299-16809d80-735a-11ea-8b8b-29566fdfdedd.png)

looks like an overflow to me

**Comment by piechottam** [comment]
Can I close the issue?
