### ISSUE TITLE
For BaseSubResult error(java.lang.NullPointerException)

### ISSUE THREAD

**Issue by XRCHAM** [dieterich-lab/JACUSA2#36]
Hi there,

When I try to add read/base stratification by -B, I met java.lang.NullPointerException error as below.
If I omit this parameter, it run smoothly.
Could you help me with this problem?

Thanks,
Xiangbin

```
DEBUG   00:00:00  DEBUG Modus!
INFO    00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC23 call-2 -s -c 20 -P RF-FIRSTSTRAND -R genome.fa -p 16 -W 1000000 -filterNM_1 7 -filterNM_2 7 -T 1 -a D,M,Y -B T2C -x -r XvsY.DP20.full X_1_dup.bam,X_2_dup.bam Y_1_dup.bam,Y_2_dup.bam
--------------------------------------------------------------------------------
INFO    00:00:01  Thread 15: Working on contig chr1:14406-1014405
INFO    00:00:01  Thread 13: Working on contig chr1:2014845-3014844
INFO    00:00:01  Thread 11: Working on contig chr1:4073741-5073740
INFO    00:00:01  Thread 12: Working on contig chr1:3017645-4017644
INFO    00:00:01  Thread 14: Working on contig chr1:1014406-2014405
INFO    00:00:01  Thread 10: Working on contig chr1:5389059-6389058
INFO    00:00:01  Thread 8: Working on contig chr1:7411598-8411597
INFO    00:00:01  Thread 9: Working on contig chr1:6389059-7389058
INFO    00:00:01  Thread 7: Working on contig chr1:8411598-9411597
INFO    00:00:01  Thread 4: Working on contig chr1:11455239-12455238
INFO    00:00:01  Thread 5: Working on contig chr1:10423467-11423466
INFO    00:00:01  Thread 3: Working on contig chr1:12455239-13455238
INFO    00:00:01  Thread 2: Working on contig chr1:13461028-14461027
INFO    00:00:01  Thread 1: Working on contig chr1:14473684-15473683
INFO    00:00:01  Thread 16: Working on contig chr1:15474339-16474338
INFO    00:00:02  Thread 6: Working on contig chr1:9421128-10421127
INFO    00:00:07  Thread 11: Working on contig chr1:16474339-17474338
java.lang.NullPointerException
        at lib.data.result.BaseSubResult.<init>(BaseSubResult.java:31)
        at jacusa.worker.CallWorker.process(CallWorker.java:57)
        at lib.worker.AbstractWorker.doWork(AbstractWorker.java:139)
        at lib.worker.AbstractWorker.processReady(AbstractWorker.java:197)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:213)
srun: error: midway2-bigmem04: task 0: Exited with exit code 255

```

**Comment by piechottam** [comment]
Could you please re-run:
* https://github.com/dieterich-lab/JACUSA2/releases/tag/v2.0.0
* without "-R genome.fa"
and report your observation.

I run your JACUSA2 call on other data (without -R genome.fa) - and this Exception was not raised...

**Comment by XRCHAM** [comment]
> Could you please re-run:
> 
> * https://github.com/dieterich-lab/JACUSA2/releases/tag/v2.0.0
> * without "-R genome.fa"
>   and report your observation.
> 
> I run your JACUSA2 call on other data (without -R genome.fa) - and this Exception was not raised...

Hi Michael,

Thanks for your reply in time. 
After removing -R genome.fa, there seems still the same bug raised.

`srun -p bigmem2 --mem=40G bash JACUSA.call2.DP20.full.sh X_1_dup.bam,X_2_dup.bam Y_1_dup.bam,Y_2_dup.bam XvsY.DP20.FULL`

##JACUSA.call2.DP20.full.sh
```
#!/bin/bash

export INP1=$1
export INP2=$2
export OUT=$3

#-RRDs------------
#CHANGE EDIT DISTANCE AGAIN
java -jar ~/bin/JACUSA_v2.0.0.jar call-2 -s -c 20 -P RF-FIRSTSTRAND -p 32 -W 1000000 -filterNM_1 7 -filterNM_2 7  -T 1 -a D,M,Y -B A2G,C2T -r ${OUT} ${INP1} ${INP2}
```
Error:
INFO   	00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC23 call-2 -s -c 20 -P RF-FIRSTSTRAND -p 32 -W 1000000 -filterNM_1 7 -filterNM_2 7 -T 1 -a D,M,Y -B A2G,C2T -r XvsY.DP20.FULL X_1_dup.bam,X_2_dup.bam Y_1_dup.bam,Y_2_dup.bam
--------------------------------------------------------------------------------
INFO   	00:00:02  Thread 31: Working on contig chr1:14406-1014405
INFO   	00:00:02  Thread 29: Working on contig chr1:2014845-3014844
INFO   	00:00:02  Thread 30: Working on contig chr1:1014406-2014405
INFO   	00:00:02  Thread 28: Working on contig chr1:3017645-4017644
INFO   	00:00:02  Thread 27: Working on contig chr1:4073741-5073740
INFO   	00:00:02  Thread 26: Working on contig chr1:5389059-6389058
INFO   	00:00:02  Thread 25: Working on contig chr1:6389059-7389058
INFO   	00:00:02  Thread 24: Working on contig chr1:7411598-8411597
INFO   	00:00:02  Thread 23: Working on contig chr1:8411598-9411597
INFO   	00:00:02  Thread 22: Working on contig chr1:9421128-10421127
INFO   	00:00:03  Thread 20: Working on contig chr1:11455239-12455238
INFO   	00:00:03  Thread 21: Working on contig chr1:10423467-11423466
INFO   	00:00:03  Thread 19: Working on contig chr1:12455239-13455238
INFO   	00:00:03  Thread 18: Working on contig chr1:13461028-14461027
INFO   	00:00:03  Thread 17: Working on contig chr1:14473684-15473683
INFO   	00:00:03  Thread 16: Working on contig chr1:15474339-16474338
INFO   	00:00:03  Thread 15: Working on contig chr1:16474339-17474338
INFO   	00:00:03  Thread 14: Working on contig chr1:17485880-18485879
INFO   	00:00:03  Thread 13: Working on contig chr1:18492939-19492938
INFO   	00:00:03  Thread 12: Working on contig chr1:19492939-20492938
INFO   	00:00:04  Thread 10: Working on contig chr1:21502078-22502077
INFO   	00:00:04  Thread 9: Working on contig chr1:22502078-23502077
INFO   	00:00:04  Thread 8: Working on contig chr1:23503085-24503084
INFO   	00:00:04  Thread 7: Working on contig chr1:24503085-25503084
INFO   	00:00:04  Thread 11: Working on contig chr1:20494925-21494924
INFO   	00:00:04  Thread 6: Working on contig chr1:25503085-26503084
INFO   	00:00:04  Thread 4: Working on contig chr1:27505288-28505287
INFO   	00:00:04  Thread 2: Working on contig chr1:29523092-30523091
INFO   	00:00:04  Thread 3: Working on contig chr1:28505288-29505287
INFO   	00:00:04  Thread 1: Working on contig chr1:30529419-31529418
INFO   	00:00:04  Thread 32: Working on contig chr1:31552483-32552482
INFO   	00:00:04  Thread 5: Working on contig chr1:26503085-27503084
INFO   	00:00:11  Thread 2: Working on contig chr1:32552483-33552482
INFO   	00:00:13  Thread 27: Working on contig chr1:33557863-34557862
INFO   	00:00:31  Thread 27: Working on contig chr1:34710125-35710124
java.lang.NullPointerException
	at lib.data.result.BaseSubResult.<init>(BaseSubResult.java:31)
	at jacusa.worker.CallWorker.process(CallWorker.java:57)
	at lib.worker.AbstractWorker.doWork(AbstractWorker.java:139)
	at lib.worker.AbstractWorker.processReady(AbstractWorker.java:197)
	at lib.worker.AbstractWorker.run(AbstractWorker.java:213)
srun: error: midway2-bigmem01: task 0: Exited with exit code 255

**Comment by XRCHAM** [comment]
By the way, I indeed use the latest version https://github.com/dieterich-lab/JACUSA2/releases/tag/v2.0.0

**Comment by piechottam** [comment]
Please try and report if Exceptions is still raised:

I have prepared a new release:
https://github.com/dieterich-lab/JACUSA2/releases/tag/v2.0.1

**Comment by XRCHAM** [comment]
> Please try and report if Exceptions is still raised:
> 
> I have prepared a new release:
> https://github.com/dieterich-lab/JACUSA2/releases/tag/v2.0.1

Thanks for the update. I find it can run without error, however, the speed becomes rather slow. With the same parameter -p 32, it could be finished in 3 hours for the whole human genome before tagging, now it was still running on chr1 taking more than 10 hours after add -B A2G.
