### ISSUE TITLE
No variants called, but no error message

### ISSUE THREAD

**Issue by ellalalalalalala** [dieterich-lab/JACUSA2#40]
Hi :) 
In the past, I always used Jacusa1. After having some problems with not called variants, I decided to test the new Jacusa2 version.

I used the latest version (2.0.2) with the following command: 
java -Xmx160g -jar $directory/JACUSA_v2.0.2-RC.jar call-2 -m 30 -q 25 -c 10 -a H:condition=1,M,B,Y -F 3 -T 1.56 -f V -r SNPs_name.out $RNA1.bam $RNA2.bam

My input files are both BAM files, which were already deduplicated , sorted and indexed via samtools (after mapping via BBMAP). The same input files (and Jacusa settings) worked perfectly with Jacusa1.

The execution of my script did not result in any error messages but the output vcf files does not contain any variants:

_##fileformat=VCFv4.2
##FILTER=<ID=B,Description="Filter potential false positive variants adjacent to read start/end.
| :distance Filter base calls within distance to feature. Default: 6
| :minRatio Minimal ratio of base calls to pass filtering. Default: 0.5
">
##FILTER=<ID=H,Description="Filter non-homozygous sites in condition 1 or 2.
| :condition Possible values for condition: 1 or 2. (Required)
">
##FILTER=<ID=M,Description="Max allowed alleles per site.
| :maxAlleles must be > 0. Default: 2
">
##FILTER=<ID=Y,Description="Filter wrong variant calls within homopolymers.
| :length must be > 0. Default: 7
">
##FORMAT=<ID=BC,Number=4,Type=Integer,Description="Base call counts A,C,G,T">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=NM_000017.4,length=1859>
##contig=<ID=NM_000018.4,length=2184>
[...... other contigs listed......]
##contig=<ID=XR_953095.1,length=808>
##contig=<ID=XR_953201.3,length=1296>
##fileDate=20210616
##source=JACUSA2 Version: 2.0.2-RC call-2 -m 30 -q 25 -c 10 -a H:condition=1,M,B,Y -F 3 -T 1.56 -f V -r SNPs_BBmap_BBDUK-IMR2_jacver2-test1_RNARNA_custrans_15072021_2021-07-15.out mapped_BBmap_BBDUK-RNAwt_jacver2-test1_IMR2_custrans_15072021_2021-07-15.sam-fixmate-sorted-deduped.bam mapped_BBmap_BBDUK-IMR2_jacver2-test1_RNAsample_custrans_15072021_2021-07-15.sam-fixmate-sorted-deduped.bam
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	11	21_

Did I make a mistake? Are there any ideas on how I could solve the problem?

Thanks a lot in advance and have a nice day :)

**Comment by piechottam** [comment]
Please rerun without
"-v V" to 
check if this is VCF output related.

**Comment by ellalalalalalala** [comment]
Hi piechottam,

I tried java _-Xmx160g -jar $PC2PFS/hpc-prf-ptma2/ptma2001/bbmap/JACUSA_v2.0.2-RC.jar call-2 -m 30 -q 25 -c 10 -a H:condition=1,M,B,Y -F 3 -T 1.56 -r SNPs_"$name"_"$date".out $RNA2_formapping $RNA1_forcalling_

This time, the output file looks like that:

_## JACUSA2 Version: 2.0.2-RC call-2 -m 30 -q 25 -c 10 -a H:condition=1,M,B,Y -F 3 -T 1.56 -r SNPs_BBmap_BBDUK-IMR2_jacver2-test1_RNARNA_custrans_22072021_2021-07-22.out /scratch/hpc-prf-ptma2/ptma2001/bbmap/mapped_BBmap_BBDUK-RNAwt_jacver2-test1_IMR2_custrans_15072021_2021-07-15.sam-fixmate-sorted-deduped.bam /scratch/hpc-prf-ptma2/ptma2001/bbmap/mapped_BBmap_BBDUK-IMR2_jacver2-test1_RNAsample_custrans_15072021_2021-07-15.sam-fixmate-sorted-deduped.bam
#contig	start	end	name	score	strand	bases11	bases21	info	filter	ref_

**Comment by ellalalalalalala** [comment]
The Output was empty, because -F 3 removed paired reads. Without -F 3 it works :)

Thanks a lot for the great support! 💯
