### ISSUE TITLE
True editing sites

### ISSUE THREAD

**Issue by ryrl9703** [dieterich-lab/JACUSA2#53]
Hello, this tool is perfect,  but I have a problem that the format of editing sites called by jacusa is a bed format that have star and end position, so I want to know which is the true editing site, start or end? Thank you very much.

**Comment by piechottam** [comment]
BED is 0-indexed -> [start, end).
* End is non-inclusive

If you want to check your sites in e.g.: IGV (1-indexed) use end position of JACUSA2 output.

**Comment by ryrl9703** [comment]
> 

Thank you for your reply
