### ISSUE TITLE
bug in script add_seq.sh

### ISSUE THREAD

**Issue by atanzer** [dieterich-lab/JACUSA2#60]
Dear Michael,

I found a bug in the preprocessing script, that reads in JACUSA2 output and just adds the sequences to the table.
Here the fix for line 55 and 57 in https://github.com/dieterich-lab/JACUSA2/blob/master/scripts/add_seq.sh.
The columns in the two awk calls are off, thus SEQ was empty and the sequences were missing in the output file

```
bedtools intersect -header -s -loj -a $jacusa -b <(
        bedtools slop -s -i <(cut -f1-6 $jacusa | awk -v OFS="\t" ' { print $1,$2,$3,"original",".",$6 } ') -g <(cut -f1-2 "$fasta.fai") -l $left -r $right | \
        bedtools getfasta -s -fi $fasta -bed - -bedOut | \
        awk -v OFS="\t" ' { print $1,$2,$3,$7,$5,$6 } '
```

Cheers,
Andrea

ps: I use bedtools v2.30.0-38-g38975ff2

**Comment by piechottam** [comment]
Thank you for the feedback and the fix!
