### ISSUE TITLE
z score threshold

### ISSUE THREAD

**Issue by anafilia** [dieterich-lab/JACUSA2#61]
Dear Jacusa2 team,
I am using call2 to perform differential RNA editing. I have 2 samples in condition1 and 5 samples in condition 2. 

Command:
java -jar JACUSA_v2.0.1.jar call-2 -F 1024 -c 2 -I -D -r results_call2.s1.out -s D1_1.fq.cl.bam,F1_1.fq.cl.bam J1_1.fq.cl.bam,H1_1.fq.cl.bam,B1_1.fq.cl.bam,C1_1.fq.cl.bam,I1_1.fq.cl.bam 

Base composition for each of the samples is identical (attached file). Any ideas what is going wrong?

Also, would you recommend a threshold to use as a cut-off to call differential editing events?
[data.txt](https://github.com/dieterich-lab/JACUSA2/files/10021984/data.txt)

Thank you

**Comment by piechottam** [comment]
Dear anafilia,

# Same Base composition
Could you please check with IGV or samtools mpileup the respective regions.

# Threshold
please check page 13 in https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-016-1432-8/MediaObjects/12859_2016_1432_MOESM1_ESM.pdf
The threshold depends on the comparison DNA vs. RNA or RNA vs. RNA.
