### ISSUE TITLE
Jacusa2 Call 2 

### ISSUE THREAD

**Issue by HaiderMDev** [dieterich-lab/JACUSA2#67]
Hello, 

I have a rather simple questions. When I am calling call 2 for Jacusa2, is it doing call 1 for each of the BAM files before the comparative analysis? Thank you.

**Comment by piechottam** [comment]
Hi,

Single sample (call-1) allows to call variants against a reference. Internally, an in silico sample is created from
information that is provided by the “MD” field in BAM files or by providing a <reference.fasta> via command
line: “-f reference.fasta”.

**Comment by HaiderMDev** [comment]
Hello,

Thank you for your response. So, just to be accurate, when you use the call 2 function then Jacusa2 is modeling the sequencing count data using the Dirichlet-multinomial distribution and using the likelihood ratio chi-squared test for analyzing statistical significance of the difference between the two samples. Therefore, you are directly comparing two samples when using call 2, and not using any information from a reference genome?

When using call 1, you can either compare the sample to an in silico condition or to the reference genome? 

Thank you for your answer in advance. I really appreciate it.
