### ISSUE TITLE
Library type and difference between call-up & pileup 

### ISSUE THREAD

**Issue by aayushraman** [dieterich-lab/JACUSA2#75]
Thank you for developing the tool. Appreciate it. I have a question regarding the Library type and strand information. I am using the Illumina TruSeq Stranded Total RNA kit and I validate using a couple of different tools, including RSeQC where I do get the `fr-firststrand` and also looked into the info provided in different blog post including the one [here](https://github.com/igordot/genomics/blob/master/notes/rna-seq-strand.md). 

1) I am confused with the option of stranded library type provided by JACUSA which are RF-FIRSTSTRAND and FR-SECONDSTRAND. Can you please explain which one I need to use? 

2) What is the different between the `call-2` and the `pileup` method? 

Thank you!

**Comment by piechottam** [comment]
1. Check for instance [this](https://onetipperday.blogspot.com/2012/07/how-to-tell-which-library-type-to-use.html) post or even better [Illumina](https://www.illumina.com/documents/products/technotes/RNASeqAnalysisTopHat.pdf), page 17 "Library Type".
2. *call-2* does variant calling and by default only outputs sites with differences. *pileup* outputs everything (~ samtools mpileup).

**Comment by aayushraman** [comment]
Thanks for the prompt reply. The difference between _call-2_ and _pileup_ is clear to me. So, is the difference between _pileup_ in Jacusa vs. _mpileup_ in the samtools the use of library type (-P argument) used by JACUSA, whereas the samtools does not use that information?

Also, I still need help understanding the stranded library type or annotation used by JACUSA. In both blog posts, I see the use of `FR-FIRSTSTRAND` and not `RF-FIRSTSTRAND` which is used by JACUSA.

**Comment by piechottam** [comment]
Yes, to your first question - The mapping qual, start, and end are missing in the JACUSA pileup.

2nd question: https://www.biostars.org/p/169942/
It mainly boils down? 
* Lib stranded:
* no -> UNSTRANDED
* yes -> FIRST or SECOND? You can check this in IGV: Orientation of reads and gene annotation are inverse -> FIRST; same orientation -> SECOND

**Comment by aayushraman** [comment]
Thank you for answering my questions!
