### ISSUE TITLE
non standard VCF output ?

### ISSUE THREAD

**Issue by gianfilippo** [dieterich-lab/JACUSA2#77]
Hi,

I ran with the following command line for RDD:
java -jar $scriptPATH/JACUSA_v2.0.4.jar call-2 -p $nCPUs -F 1024 -a I,B,S,M,H:condition=1 -r $outPATH/$outFILE -f V -b $bedPATH/$bedFILE -R $genPATH/$genFILE $wgsPATH/$smpID/${smpID}.merged.aligned.sorted.bam $rnaPATH/$smpID/${smpID}.Aligned.sortedByCoord.bam

bedFILE: REDIportal converted to bed file

The output VCF file seems to have non standard header, as for instance, FixVcfHeader (picard) stops with an error.
I also tried to filter with "vcftools --minDP", but it results in the following error: "Error: Require Genotypes in variant file in order to filter genotypes by Depth."
I also tried simply bcftools stats, but the "# DP, Depth distribution" is empty

Also, JACUSA2helper does not read vcfs.

Am I making a mistake somewhere ?

Thanks

**Comment by piechottam** [comment]
Dear User,

* JACUA2 uses [hts](https://www.htslib.org/) - there are some known issues (problems with VCF). I am planning to update hts to a more recent version. 
* If you need to use BED file format (for bedtools for instance) I recommend to use default JACUSA2 output file format - the first six columns of JACUSA2 output correspond to BED6 (https://genome.ucsc.edu/FAQ/FAQformat.html#format1).

**Comment by gianfilippo** [comment]
Thanks
