### ISSUE TITLE
Strandedness Issue -- opposite results for Reditools2 and JACUSA2

### ISSUE THREAD

**Issue by ekofman** [dieterich-lab/JACUSA2#78]
Hi, 

I am running reditools2 and JACUSA2 on the same .bam file.
To confirm the strand-specificity of my data, I used RSeQC, which provides a tool to infer the strand-specificity of RNA-seq data, on my .bam and it output:

```
>> infer_experiment.py -r reference.bed -i sample.bam

Reading reference gene model reference.bed ... Done
Loading SAM/BAM file ...  Total 200000 usable reads were sampled

This is SingleEnd Data
Fraction of reads failed to determine: 0.0471
Fraction of reads explained by "++,--": 0.0378
Fraction of reads explained by "+-,-+": 0.9152

```

Based on this, it seems that most of my reads are strand specific and follow the convention for second-strand sequencing (FR-SECONDSTRAND). Thus, I would expect to use the following:

```
For REDItools2: Use -s 2 to specify second-strand specificity.
For JACUSA2: Use -P FR-SECONDSTRAND to match the strand-specific setting for your data.
```

I am thus calling:

`java -jar JACUSA_v2.0.4.jar call-1 -P FR-SECONDSTRAND -p 32 -q 30 -m 20 -r sample.edits.bed -f B sample.bam `

However, I seem to be getting the exact opposite edits (reverse complement) as what I got using -s 2 in REDItools2... have there been any other issues with this? Is there a chance it is incorrect? It seems one of these two tools is incorrectly flipping strand. Unless there is another option as to why they would present opposite results...?

**Comment by ekofman** [comment]
[sample_bam.zip](https://github.com/user-attachments/files/17580836/sample_bam.zip)


here is a subset of reads from the bam I running with ^

**Comment by piechottam** [comment]
Hi,

according to https://rseqc.sourceforge.net/#infer-experiment-py
[...]
    +-,-+

    read mapped to ‘+’ strand indicates parental gene on ‘-’ strand

    read mapped to ‘-’ strand indicates parental gene on ‘+’ strand
[...]
and the result:
[...]
Fraction of reads explained by "+-,-+": 0.9152
[...]
Your library type would be: RF-FIRSTSTRAND -> use -P RF-FIRSTSTRAND in JACUSA2 and your problems should go away.

**Comment by ekofman** [comment]
Great, thank you for the clarification! Glad it was just user error.

**Comment by piechottam** [comment]
np.
