### ISSUE TITLE
question about overlap between JACUSA2 and REDItools

### ISSUE THREAD

**Issue by gianfilippo** [dieterich-lab/JACUSA2#79]
Hi,

this is more of a question

I ran JACUSA2 and REDItools on the same sample (RNA and DNA). I find little overlap between the calls. 
I see about 25% of the JACUSA calls shared with REDItools.

Is this expected or does it seem unexpected ?

Thanks

**Comment by piechottam** [comment]
No, this is not expected.

Did you check the default parameters for minimal BASQ, minimal mapping quality of each Tool?
How do you calculate the overlap? -> try unstranded overlap.
What type of sites are missing in JACUSA2 output? What is their coverage?

**Comment by gianfilippo** [comment]
Hi, thanks.
Read/base Quality are set to be the same, 20.
I created a basic bed fie from REDItools2 output and intersected it with  JACUSA2 bed output file (bedtools intersect -a $REDIfile -b $JACUSAfile) 
I used REDIportal to annotated and select known events calls REDItools2
I also used REDIportal (after converting it to a 0-based bed file) as input to JACUSA2
For instance, I get the following N of calls
REDItools2 314490 
JACUSA2 157450
intersection 37438

I understand the filters may not be fully equivalent, but I was expecting ore calls in the intersection.
That said, I feel I am making a mistake somewhere. What do you think ?
Thanks

**Comment by piechottam** [comment]
Ty.
That overlap is strangely low.  Do you mind sending me the command lines for each tool?

**Comment by gianfilippo** [comment]
Hi, I am very sorry, I reviewed the code and reran the contrasts and intersection is actually very good.
Best
