### ISSUE TITLE
Question about splitting reads that contain Ns in their cigar string

### ISSUE THREAD

**Issue by gianfilippo** [dieterich-lab/JACUSA2#80]
Hi,

GATK recommends splitting reads that contain Ns in their cigar string. 
You do not seem to require it as preprocessing step. 
Do you not expect it to have any positive effect in terms of FP ?

Thanks

**Comment by piechottam** [comment]
We filter/mark the results -> "jacusa2.jar -a D ..."
[...]
 -a <FEATURE-FILTER>   Chain of FEATURE-FILTER. Join FEATURE-FILTER D and I with ',' and add options with ':'
                       e.g.: D,I:I_OPTION1:I_OPTION2=I_VALUE2
                       B Filter potential false positive variants adjacent to read start/end.
                       | :distance Filter base calls within distance to feature. Default: 6
                       | :minRatio Minimal ratio of base calls to pass filtering. Default: 0.5
                       D Combines Filters: I + B + S
                       | :distance Filter base calls within distance to feature. Default: 6
                       | :minRatio Minimal ratio of base calls to pass filtering. Default: 0.5
                       I Filter potential false positive variants adjacent to INDEL
                       | position(s).
                       | :distance Filter base calls within distance to feature. Default: 6
                       | :minRatio Minimal ratio of base calls to pass filtering. Default: 0.5
                       S Filter potential false positive variants adjacent to splice site(s).
                       | :distance Filter base calls within distance to feature. Default: 6
                       | :minRatio Minimal ratio of base calls to pass filtering. Default: 0.5

This will mark any variants that are biased towards reads start/end or adjacent to Splice site by adding a "D" to the filter column of the output.

I haven't used "splitncigarreads" so far.

**Comment by gianfilippo** [comment]
Thanks. I will read better the manual.
